### ISSUE TITLE
ADB install tool

### ISSUE THREAD

**Issue by elreydetoda** [chenhan1218/packer-anbox#1]
So on this line:
https://github.com/chenhan1218/packer-anbox/blob/fba35fcaf1b399326dd53165d40dcb1ae1d577ca/packer_templates/ubuntu/scripts/anbox.sh#L11

you install the adb package vs what the [anbox docs](https://docs.anbox.io/userguide/install_apps.html) say to install the `android-tools-adb` package.

Just curious if there is a difference, and why you chose the adb package vs the other one?

**Comment by chenhan1218** [comment]
@elreydetoda 
Thanks your suggestion!
Previously I select a workable android adb utility to install.
Now that the anbox doc provide instruction for the android adb tools. Then that's follow the doc and change the scripts.

I will fix the issue.

**Comment by chenhan1218** [comment]
I have re-built the anbox vagrant image.
The latest image version 20200329 address this issue:

Check it on vagrant official website:
https://app.vagrantup.com/chenhan/boxes/anbox

**Comment by elreydetoda** [comment]
cool, thanks :slightly_smiling_face:
